### ISSUE TITLE
parcel-transformer-svelte: Cannot read property 'preprocessors' of null

### ISSUE THREAD

**Issue by berkant** [orlov-vo/parcel-transformer-svelte#7]
Output:
```
Build failed.
parcel-transformer-svelte: Cannot read property 'preprocessors' of null
TypeError: Cannot read property 'preprocessors' of null
    at Object.transform (/Users/berkant/workspace/xxx/yyy/node_modules/parcel-transformer-svelte/index.js:45:16)
    at async runTransformer (/Users/berkant/workspace/xxx/yyy/node_modules/@parcel/core/lib/Transformation.js:472:3)
    at async Transformation.runPipeline (/Users/berkant/workspace/xxx/yyy/node_modules/@parcel/core/lib/Transformation.js:257:36)
    at async Transformation.runPipelines (/Users/berkant/workspace/xxx/yyy/node_modules/@parcel/core/lib/Transformation.js:193:40)
    at async Transformation.run (/Users/berkant/workspace/xxx/yyy/node_modules/@parcel/core/lib/Transformation.js:111:19)
    at async Child.handleRequest (/Users/berkant/workspace/xxx/yyy/node_modules/@parcel/workers/lib/child.js:165:9)
```

package.json:
```json
{
  "name": "yyy",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "start": "parcel serve src/index.html --no-autoinstall"
  },
  "devDependencies": {
    "parcel": "^2.0.0-beta.1",
    "parcel-transformer-svelte": "^1.0.3",
    "svelte": "^3.23.2"
  }
}
```

index.html:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello World!</title>
    <script>
        import App from './App.svelte';

        const app = new App({
            target: document.body,
        });
    </script>
</head>
<body>
    Hello World!
</body>
</html>
```

App.svelte:
```svelte
<strong>Hello from App.svelte!</strong>
```

**Comment by w7it** [comment]
Thanks for reporting! The error should go away in new 1.0.4 version
